### ISSUE TITLE
Option to mark as dead if individual has no death date

### ISSUE THREAD

**Issue by a2line** [woyczek/GenewParse#3]
By default in GeneWeb, people are left alive even if born a long long time ago. We need a new option to be able to mark them as deceased (overwise we'll need to edit all individual one by one to do it).

If there is no death date for an individual (him or her), the option will replace the `empty death year` by `%2B`. (In forms, we add an ASCII `+` in death (†) year that is encoded %2B in URL.)

**Comment by a2line** [comment]
When adding those %2B the year of the death must be empty but the first name and surname of the individual must not be empty (no need to create an unknown person ? ? with only “is dead” as data).

**Comment by woyczek** [comment]
A command line option ?

**Comment by a2line** [comment]
It could be a nice option, yes, `mark all individual as dead`, you can pick the letter!

**Comment by woyczek** [comment]
Fix by chainsaw in 1.9.
