### ISSUE TITLE
3rd weddings not parsed

### ISSUE THREAD

**Issue by a2line** [woyczek/GenewParse#4]
It looks like that the 3rd wedding of the Sosa 2 of this [table](https://gw.geneanet.org/drumpler?lang=fr&pz=dieter+gustav&nz=rumpler&ocz=0&m=A&p=urban&n=rech&oc=1&sosab=10&color=&t=Z&birth=on&birth_place=on&marr=on&marr_date=on&marr_place=on&child=on&death=on&death_place=on&death_age=on&occu=on&gen=on&repeat=on&v=3) is not parsed at all (on this case the 3rd is the wedding of the two ancestors).

**Comment by woyczek** [comment]
Fixed 1.8
