### ISSUE TITLE
First names including a comma are not parsed

### ISSUE THREAD

**Issue by a2line** [woyczek/GenewParse#5]
First names like “Jean, Marcel” are parsed into a “R”. I think it is because of the comma it's the only diffenrence I see. I can find an example if needed to help debugging.

**Comment by woyczek** [comment]
Le 28 juin 2018 19:56:48 GMT+02:00, A2 <notifications@github.com> a écrit :
>First names like “Jean, Marcel” are parsed into a “R”. I think it is
>because of the comma it's the only diffenrence I see. I can find an
>example if needed to help debugging.

Some people really have a comma in its name!?
-- 
Gaétan RYCKEBOER

"Là où il ya une volonté, il ya un chemin" 
-- Proverbe flamand

**Comment by a2line** [comment]
It's a typographic way to type first names, to be sure different first names are “better” identified. I don't use it but some people do. That allow to distinguish : “Jean Pierre Louis Nicolas”, “Jean Pierre, Louis, Nicolas”, “Jean, Pierre Louis, Nicolas”, “Jean, Pierre, Louis, Nicolas”, etc. Looking for an example.

**Comment by a2line** [comment]
On [this table](https://gw.geneanet.org/dibos?lang=fr&m=A&p=francoise+victorine&n=deny&sosab=10&color=&t=Z&birth=on&birth_place=on&marr=on&marr_date=on&marr_place=on&child=on&death=on&death_place=on&death_age=on&occu=on&gen=on&repeat=on&v=10), the first name of Sosa 1 is parsed to `Y` but should be `Françoise Victorine` or `Françoise, Victorine`.

**Comment by woyczek** [comment]
Fixed 1.8.
