### ISSUE TITLE
Detection of implexes fails after sosa 999

### ISSUE THREAD

**Issue by a2line** [woyczek/GenewParse#6]
The parsing of implexes probably fails because of the hardcoded &amp;nbsp; past Sosa number 999.

[Sosa 1330 of this table](https://gw.geneanet.org/pilletm?birth=on&birth_place=on&child=on&color=&death=on&death_age=on&death_place=on&gen=on&lang=fr&m=A&marr=on&marr_date=on&marr_place=on&n=guir&nz=pillet&occu=on&ocz=0&p=romain&pz=clemence&repeat=on&sosab=10&t=Z&v=14) should be “=1320” (`-> 1&nbsp;320`) [same for the next implex 2651=1313].

**Comment by woyczek** [comment]
Thousand separator feature.
Added for french.
